spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/team10_dev
    username: devuser
    password: devpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # 개발 환경에서는 매번 테이블을 새로 생성
    show-sql: true # SQL 쿼리 로그 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 100        # 배치 처리 최적화
        order_inserts: true     # INSERT 순서 최적화
        order_updates: true     # UPDATE 순서 최적화

  cloud:
    gcp:
      storage:
        enabled: false   # dev 환경은 MinIO 사용, GCP Storage 자동설정 비활성화
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      database: chatdb
      username: admin
      password: dhalwk12!
      authentication-database: admin

# 테스트용
cloud:
  storage:
    type: minio
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: dhalwk12!
    bucket-name: dev-bucket
